### ISSUE TITLE
Grammarly shows improvements

### ISSUE THREAD

**Issue by szepeviktor** [zakirullin/cognitive-load#4]
If you copy and paste the text section by section Grammarly will offer you suggestions.
https://www.grammarly.com/grammar-check

A new star 🌟 is born: https://www.deepl.com/write

**Comment by zakirullin** [comment]
Thanks, I'll put all the text through it!

**Comment by zakirullin** [comment]
@szepeviktor I've been heavily using deepl and other AI based tools, but I haven't heard about deepl/write. Thanks! 

So many new AI tools, every product is not backed by generative LMs
